blog/urls.py
from django.urls import path , include


from . import views
# from .views import ArticleList

app_name = 'blog'

urlpatterns = [
    # class base view
    # path('' , ArticleList.as_view() , name='index'),
    path('' , views.index , name='index'),
    path('test/' , views.test , name='test'),
    path('create/' , views.create , name='create'),
    path('posts/<int:id>/' , views.post , name='posts'),
    path('articles/' , views.article , name="articles"),
    path('articles/<slug:slug>', views.detail , name="detail_artilce"),
    path('categories/<slug:slug>' , views.category , name="category"),
]

personal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('blog.urls','blog'),namespace='blog')),
    path('account/',include(('account.urls' , 'account'),namespace='account')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


#static files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/article.html
{% extends 'index.html' %}


{% block head %}
    article

{% endblock head %}



{% block content %}
    {% for article in articles %}
        <a href="{{ article.slug }}"> {{ article.title }} </a>

        <p> 
            {{ article.description | truncatechars_html:120 }}
        </p>

    {% endfor %}

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
	
	{% block head %}
		
	{% endblock head %}
			  
  </title>
  <!-- favicon -->
  <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" type="image/x-icon">
  <!-- bootstrap -->
  <link rel="stylesheet" href="{% static 'assets/css/bootstrap-rtl.min.css' %}">
  <!-- fontawesome -->
  <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
  <!-- Flat Icon -->
  <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
  <!-- animate -->
  <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
  <!-- Owl Carousel -->
  <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
  <!-- magnific popup -->
  <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
  <!-- AOS css -->
  <link rel="stylesheet" href="{% static 'assets/css/aos.css' %}">
  <!-- stylesheet -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <!-- responsive -->
  <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
</head>

<body>

  <!-- preloader area start -->
  <div class="preloader" id="preloader">
    <div class="preloader-inner">
      <div class="cube-wrapper">
        <div class="cube-folding">
          <span class="leaf1"></span>
          <span class="leaf2"></span>
          <span class="leaf3"></span>
          <span class="leaf4"></span>
        </div>
        <span class="loading" data-name="Loading">در حال بارگذاری</span>
      </div>
    </div>
  </div>
  <!-- preloader area end -->

  <!-- Navebar Area start -->
  <header class="navigation">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 p-0">
          <nav class="navbar navbar-expand-lg navbar-light">
            <a class="navbar-brand" href="index.html">
              <img src="/static/assets/images/logo-color.png" alt="">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu"
              aria-controls="mainmenu" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
						<div class="collapse navbar-collapse" id="mainmenu">
							<ul class="navbar-nav ml-auto">
								<li class="nav-item">
									<a class="nav-link" href="/">صفحه اصلی</a>
								</li>
								{% for category in categories %}
                
                  {% if category.parent == None %}
                  <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {{ category.title }}
                    </a>
                    {% if category.children.all %}
                      {% for cat in category.children.all %}
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="blog-grid.html">
                          <i class="fas fa-chevron-left"></i> {{ cat.title }}
                          </a>
                          {% if cat.children.all %}
                            {% include 'category_loop.html' %}
                          {% endif %}
                      </div>
                      {% endfor %}
                    {% endif %}
                      
                  </li>   
                  {% endif %}
                  
                {% endfor %}
								
                <li class="nav-item">
									<a class="nav-link" href="#about">درباره ما</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="#contact">ارتباط با ما</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- Navebar Area End -->


<!-- Breadcrumb Area Start -->
<section class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h4 class="title">
					
          {% block title %}
            
          {% endblock title %}
            
                </h4>
                <ul class="breadcrumb-list">
					
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Area End -->

	<!-- Blog Page Grid Area Start -->
	
	{% block content %}
		
	{% endblock content %}
		
	
	<!-- Blog Page Grid Area End -->


  <!-- Footer Section Start -->
  <footer class="footer" id="footer">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="footer-info-area">
            <div class="footer-logo">
              <a href="#" class="logo-link">
                <img src="/static/assets/images/logo-color.png" alt="">
              </a>
            </div>
            <div class="text">
							<p>هر گونه کپی برداری و انتشار غیرقانونی از سایت پیگرد قانونی
                دارد. 
              </p>
            </div>
          </div>
          <div class="fotter-social-links">
            <ul>
              <li>
                <a href="#" class="facebook">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li>
                <a href="#" class="twitter">
                  <i class="fab fa-twitter"></i>
                </a>
              </li>
              <li>
                <a href="#" class="linkedin">
                  <i class="fab fa-linkedin-in"></i>
                </a>
              </li>
              <li>
                <a href="#" class="google-plus">
                  <i class="fab fa-google-plus-g"></i>
                </a>
              </li>
              <li>
                <a href="#" class="dribbble">
                  <i class="fab fa-dribbble"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="copy-bg text-center">
			<p>
        © 2020 <a href="zeinab.pirvali">پیرولی</a> تمام حقوق مادی و
        معنوی سایت محفوظ می باشد.
      </p>
      </p>
    </div>
  </footer>
  <!-- Footer Section End -->

  <!-- Back to Top Start -->
  <div class="bottomtotop">
    <i class="fa fa-chevron-left"></i>
  </div>
  <!-- Back to Top End -->


  <!-- jquery -->
  <script src="{% static 'assets/js/jquery.js' %}"></script>
  <!-- popper -->
  <script src="{% static 'assets/js/popper.min.js' %}"></script>
  <!-- bootstrap -->
  <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
  <!-- way poin js-->
  <script src="{% static 'assets/js/waypoints.min.js' %}"></script>
  <!-- owl carousel -->
  <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
  <!-- magnific popup -->
  <script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>
  <!-- aos js-->
  <script src="{% static 'assets/js/aos.js' %}"></script>
  <!-- counterup js-->
  <script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>
  <!-- easing js-->
  <script src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>
  <!-- Map js -->
	<!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7eALQrRUekFNQX71IBNkxUXcz-ALS-MY&amp;sensor=false"></script> -->
	<script src="{% static 'assets/js/gmap.js' %}"></script>
  <!-- main -->
  <script src="{% static 'assets/js/contact.js' %}"></script>
  <!-- main -->
  <script src="{% static 'assets/js/main.js' %}"></script>
</body>


</html>

templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
	پرسنال ادمین
{% endblock head %}


{% block title %}
وبلاگ پرسنال ادمین
{% endblock title %}
	
	
{% block content %}
<section class="blog-page single-blog-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="row">
					
					{% for article in category.articles.all %}
					
					<div class="col-lg-6 col-md-6">
						<div class="single-blog">
							<div class="img">
								<img src="{{ article.image.url }}" alt="">
							</div>
							<div class="content">
								<ul class="top-meta">
									<li>
										<p class="date">
											{{ article.publish }}
										</p>
									</li>
									<li>
										<p class="post-by">
											توسط مدیر
										</p>
									</li>
								</ul>
								<a href="{% url 'blog:detail_artilce' article.slug %}">
									<h4 class="title">
										{{ article.title }}
									</h4>
								</a>
							</div>
						</div>
					</div>
					{% endfor %}

				</div>
				<div class="row">
					<div class="col-12 d-flex justify-content-center">
						<nav aria-label="Page navigation example">
							<ul class="pagination">
								<li class="page-item">
									<a class="page-link" href="#" aria-label="Previous">
										<span aria-hidden="true"><i class="fas fa-angle-double-right"></i></span>
									</a>
								</li>
								<li class="page-item"><a class="page-link" href="#">1</a></li>
								<li class="page-item"><a class="page-link active" href="#">2</a></li>
								<li class="page-item"><a class="page-link" href="#">3</a></li>
								<li class="page-item">
									<a class="page-link" href="#" aria-label="Next">
										<span aria-hidden="true"><i class="fas fa-angle-double-left"></i></span>
									</a>
								</li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				
				<div class="categori-widget">
					<h4 class="title">
						دسته بندی
					</h4>
					<ul class="cat-list">
						{% for category in categories %}
						<li>
							<a href="{{ category.slug }}">
								<p>
									{{ category.title }}
								</p>
								<span class="count">
								33
								</span>
							</a>
						</li>	
						{% endfor %}
					</ul>
				</div>
				<div class="latest-post-widget">
					<h4 class="title">
					آخرین خبرها
					</h4>
					<ul class="post-list">
						<li>
							<div class="post">
								<div class="post-img">
									<img src="/static/assets/images/blog/img1.png" alt="">
								</div>
								<div class="post-details">
									<a href="#" class="post-title">
									لورم ایپسوم متن ساختگی 
									</a>
								</div>
							</div>
						</li>
						<li>
							<div class="post">
								<div class="post-img">
									<img src="/static/assets/images/blog/img2.png" alt="">
								</div>
								<div class="post-details">
									<a href="#" class="post-title">
									لورم ایپسوم متن ساختگی
									</a>
								</div>
							</div>
						</li>
						<li>
							<div class="post">
								<div class="post-img">
									<img src="/static/assets/images/blog/img3.png" alt="">
								</div>
								<div class="post-details">
									<a href="#" class="post-title">
									لورم ایپسوم متن ساختگی
									</a>
								</div>
							</div>
						</li>
						<li>
							<div class="post">
								<div class="post-img">
									<img src="/static/assets/images/blog/img4.png" alt="">
								</div>
								<div class="post-details">
									<a href="#" class="post-title">
								لورم ایپسوم متن ساختگی
									</a>
								</div>
							</div>
						</li>
					</ul>
				</div>
				<div class="newsletter-widget">
					<h4 class="title">
							خبرنامه 
					</h4>
					<form action="#">
						<input type="text" class="input-field" placeholder="ایمیل خود را وارد کنید">
						<button type="submit" class="mybtn2">
			<span>عضویت</span>
		  </button>
					</form> 
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}
	

templates/category_loop.html
{% for cat in cat.children.all %}
<div class="dropdown-menu">
    <a class="dropdown-item" href="blog-grid.html">
        <i class="fas fa-chevron-left"></i> {{ cat.title }}
    </a>
</div>
{% endfor %}

templates/create.html
{% extends "index.html" %}

	{% block head %}
		create
	{% endblock head %}


    <br>
    <br>
    <br>
    <br>
    <h1> dashboard </h1>

{{ expenses.0.user }}

templates/detail.html
{% extends 'base.html' %}

{% block head %}
    {{ article.title }}
{% endblock head %}


{% block title %}
{{ article.title }}
{% endblock title %}
    

{% block content %}

<section class="blog-page single-blog-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
      <div class="single-blog-details">
          <div class="img">
              <img src="{{ article.image.url }}" alt="">
          </div>
          <div class="content">
              <ul class="top-meta">
                  <li>
                      <p class="date">
                            {{ article.publish }}
                      </p>
                  </li>
                  <li>
                      <p class="post-by">
                          توسط مدیر
                      </p>
                  </li>
              </ul>
              <a href="#">
                  <h4 class="title">
                      {{ article.title }}
                  </h4>
              </a>
              <div class="text-area">
                  
                  {{ article.description | safe | linebreaks }}
              </div>
          </div>
      </div>
      <div class="comment-area">
          <h4 class="title">
              نظرات
          </h4>
          <ul class="comment-box-area">
              <li>
                <div class="comment-box">
                  <div class="left">
                    <div class="img">
                      <img src="assets/images/blog/comment1.png" alt="">
                    </div>
                    <a class="replay" href="#">پاسخ</a>
                  </div>
                  <div class="right">
                    <h5 class="name">
                     زینب پیرولی
                    </h5>
                    <p class="date">10 آذر, 1399</p>
                    <div class="text">
                      <p>  این یک متن تستی است برای نظر دادن امیدواریم نظرات
                        ارزشمندتان را با ما در میان بگذارید. </p>
                    </div>
                  </div>
                </div>
                <div class="comment-box replay-comment">
                  <div class="left">
                    <div class="img">
                      <img src="assets/images/blog/comment2.png" alt="">
                    </div>
                    <a class="replay" href="#">پاسخ</a>
                  </div>
                  <div class="right">
                    <h5 class="name">
                      بیل گیتس
                    </h5>
                    <p class="date">10 آذر, 1399</p>
                    <div class="text">
                      <p>  این یک متن تستی است برای نظر دادن امیدواریم نظرات
                        ارزشمندتان را با ما در میان بگذارید. </p>
                    </div>
                  </div>
                </div>
              </li>
              <li>
                <div class="comment-box">
                  <div class="left">
                    <div class="img">
                      <img src="assets/images/blog/comment2.png" alt="">
                    </div>
                    <a class="replay" href="#">پاسخ</a>
                  </div>
                  <div class="right">
                    <h5 class="name">
                      بیل گیتس
                    </h5>
                    <p class="date">10 آذر, 1399</p>
                    <div class="text">
                      <p>  این یک متن تستی است برای نظر دادن امیدواریم نظرات
                        ارزشمندتان را با ما در میان بگذارید. </p>
                    </div>
                  </div>
                </div>
                <div class="comment-box replay-comment">
                  <div class="left">
                    <div class="img">
                      <img src="assets/images/blog/comment1.png" alt="">
                    </div>
                    <a class="replay" href="#">پاسخ</a>
                  </div>
                  <div class="right">
                    <h5 class="name">
                     زینب پیرولی
                    </h5>
                    <p class="date">10 آذر, 1399</p>
                    <div class="text">
                      <p>  این یک متن تستی است برای نظر دادن امیدواریم نظرات
                        ارزشمندتان را با ما در میان بگذارید. </p>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
      </div>
      <div class="write-comment">
          <h4 class="title">
            دیدگاه خودرا با ما در میان بگذارید
          </h4>
          <form action="#">
              <div class="row">
                <div class="col-md-6">
                  <input type="text" class="input-field borderd" placeholder="نام خود را وارد کنید">
                </div>
                <div class="col-md-6">
                  <input type="email" class="input-field borderd" placeholder="ایمیل خود را وارد کنید">
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12">
                  <textarea class="input-field borderd textarea" placeholder="متن نظر خود را بنویسید"></textarea>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12">
                  <button class="mybtn2" type="submit">
                    <span>ارسال دیدگاه</span>
                  </button>
                </div>
              </div>
            </form>
      </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
    

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load base_tags %}

{% block head %}
	پرسنال ادمین
{% endblock head %}


{% block title %}
وبلاگ پرسنال ادمین
{% endblock title %}
	
	
{% block content %}
<section class="blog-page single-blog-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8">
				<div class="row">
					
					{% for article in articles %}
					
					<div class="col-lg-6 col-md-6">
						<div class="single-blog">
							<div class="img">
								<img src="{{ article.image.url }}" alt="">
							</div>
							<div class="content">
								<ul class="top-meta">
									<li>
										<p class="date">
											{{ article.jpublish }}
										</p>
									</li>
									<li>
										<p class="post-by">
											توسط {{ article.author }}
										</p>
									</li>
								</ul>
								<a href="{% url 'blog:detail_artilce' article.slug %}">
									<h4 class="title">
										{{ article.title }}
									</h4>
								</a>
							</div>
						</div>
					</div>
					{% endfor %}

				</div>
				<div class="row">
					<div class="col-12 d-flex justify-content-center">
						<nav aria-label="Page navigation example">
							<ul class="pagination">
								
								{% if articles.has_previous %}
								<li class="page-item">
									<a class="page-link" href="?page={{ articles.previous_page_number }}" aria-label="Previous">
										<span aria-hidden="true"><i class="fas fa-angle-double-right"></i></span>
									</a>
								</li>
								{% endif %}
								{% for i in articles.paginator.page_range %}
								{% if articles.number == i %}
								<li class="page-item"><a class="page-link active" href="?page={{ i }}">{{ i }}</a></li>
								{% else %}
								<li class="page-item"><a class="page-link " href="?page={{ i }}">{{ i }}</a></li>
								
								{% endif %}
								{% endfor %}
									
								{% if articles.has_next %}
								<!-- <li class="page-item"><a class="page-link" href="?page={{ articles.paginator.num_pages }}">{{ articles.paginator.num_pages }}</a></li> -->

								<li class="page-item">
									<a class="page-link" href="?page={{ articles.next_page_number }}" aria-label="Next">
										<span aria-hidden="true"><i class="fas fa-angle-double-left"></i></span>
									</a>	
								</li>
								{% endif %}
										
									
							</ul>
						</nav>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				
				<div class="categori-widget">
					<h4 class="title">
						دسته بندی
					</h4>
					<ul class="cat-list">
						{% for category in categories %}
						{% if category.parent == None %}
						<li>
							<a href="{% url 'blog:category' category.slug %}">
								<p>
									{{ category.title }}
								</p>
								<span class="count">
									33
								</span>
							</a>
							{% if category.children.all %}
							<ul class="cat-list">
								{% for category in category.children.all %}
								<li>
									<a href="{% url 'blog:category' category.slug %}">
										<p>
											{{ category.title }}
										</p>
										<!-- <span class="count">
											33
										</span> -->
									</a>
									
								</li>
								{% endfor %}
							</ul>
							{% endif %}
						</li>
						{% endif %}
						{% endfor %}
					</ul>
				</div>
				<div class="latest-post-widget">
					<h4 class="title">
					آخرین خبرها
					</h4>
					<ul class="post-list">
						<li>
							<div class="post">
								<div class="post-img">
									<img src="/static/assets/images/blog/img1.png" alt="">
								</div>
								<div class="post-details">
									<a href="#" class="post-title">
									لورم ایپسوم متن ساختگی 
									</a>
								</div>
							</div>
						</li>
						<li>
							<div class="post">
								<div class="post-img">
									<img src="/static/assets/images/blog/img2.png" alt="">
								</div>
								<div class="post-details">
									<a href="#" class="post-title">
									لورم ایپسوم متن ساختگی
									</a>
								</div>
							</div>
						</li>
						<li>
							<div class="post">
								<div class="post-img">
									<img src="/static/assets/images/blog/img3.png" alt="">
								</div>
								<div class="post-details">
									<a href="#" class="post-title">
									لورم ایپسوم متن ساختگی
									</a>
								</div>
							</div>
						</li>
						<li>
							<div class="post">
								<div class="post-img">
									<img src="/static/assets/images/blog/img4.png" alt="">
								</div>
								<div class="post-details">
									<a href="#" class="post-title">
								لورم ایپسوم متن ساختگی
									</a>
								</div>
							</div>
						</li>
					</ul>
				</div>
				<div class="newsletter-widget">
					<h4 class="title">
							خبرنامه 
					</h4>
					<form action="#">
						<input type="text" class="input-field" placeholder="ایمیل خود را وارد کنید">
						<button type="submit" class="mybtn2">
			<span>عضویت</span>
		  </button>
					</form> 
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}
	

templates/posts.html
{% extends "index.html" %}
<html>

    {% block head %}
        show post
    {% endblock head %}


{% block content %}
	{{ post.title}}
    <hr>

    {{ post.body  }}    
    <br>
    {{ post.text|safe|truncatechars_html:120}}
{% endblock content %}




</html>